#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/butter-kvmd ] && . /etc/conf.d/butter-kvmd

get_pid() {
	ps aux | grep -v grep | grep '/usr/bin/python2 /usr/bin/butter kvmd' | awk '{print $2}'
}

case "$1" in
  start)
    stat_busy "Starting Butter KVM Daemon"

    PID=$(get_pid)
    if [ -z "$PID" ]; then
      [ -f /var/run/butter-kvmd.pid ] && rm -f /var/run/butter-kvmd.pid
      # RUN
      /usr/bin/butter kvmd
      #
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        echo $(get_pid) > /var/run/butter-kvmd.pid
        add_daemon butter-kvmd
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping Butter KVM Daemon"
    PID=$(get_pid)
    # KILL
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    #
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      rm -f /var/run/butter-kvmd.pid &> /dev/null
      rm_daemon butter-kvmd
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "usage: $0 {start|stop|restart}"
esac

exit 0
