#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/butter-vmcache ] && . /etc/conf.d/butter-vmcache

PID=$(ps -ef | grep '/usr/bin/butter vmcache' | grep -v grep | awk '{print $2}')

case "$1" in
start)
	stat_busy "Starting VM Cache Daemon"
	if [[ -z "$PID" ]]
    then
        butter vmcache start
		add_daemon butter-vmcache
		stat_done
	else
		stat_fail
		exit 1
	fi
	;;

stop)
	stat_busy "Stopping VM Cache Daemon"
	if [[ ! -z "$PID" ]]  && kill "$PID" &>/dev/null
    then
        butter vmcache stop
		rm_daemon butter-vmcache
		stat_done
	else
		stat_fail
		exit 1
	fi
	;;

restart)
	$0 stop
	$0 start
	;;

*)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1

esac
